h5ad_file: "./data/covid_atlas/dis_scement_full_full_intersect.h5ad"
row_major_h5_file: "./data/covid_atlas/dis_scement_full_full_intersect.rmajor.h5"
gene_id_col: "gene_name/values"
tf_csv_file: "data/pbmc/trrust_tf.txt"
nroundup: 3
output_file: "./out/covid.1266K/covid.1266K.11K.gb_grn.h5"
#mode: gb_grn
mode: cv_gb
gbm_params:
  verbose: 0
  num_threads: 2
n_sample_genes: 500
