h5ad_file: "./data/rsc.20k/adata_lei.100k.20k.h5ad"
row_major_h5_file: "./data/rsc.20k/adata_lei.100k.20k.rmajor.h5"
misi_data_file: "./out/rsc.20k/adata.100K.20K.hist_misidata.h5"
hist_data_file: "./out/rsc.20k/adata.100K.20K.nodes.h5"
puc_file: "./out/rsc.20k/adata.100K.20K.hist_lmr_puc.h5"
pidc_file: "./out/rsc.20k/adata.100K.20K.hist_lmr_pidc.h5"
#
nrounds: 0
nsamples: 0
nobs: 0
nvars: 0
mode:
  - hist_nodes
tbase: "2"
save_nodes: False
save_node_pairs: True
