h5ad_file: "./data/rsc.5k/adata_lei.100k.5k.h5ad"
row_major_h5_file: "./data/rsc.5k/adata_lei.100k.5k.rmajor.h5"
misi_data_file: "./out/rsc.5k/adata.100K.5K.dmisidata.h5"
hist_data_file: "./out/rsc.5k/adata.100K.5K.hist.h5"
puc_file: "./out/rsc.5k/adata.100K.5K.lmr_puc.h5"
pidc_file: "./out/rsc.5k/adata.100K.5K.lmr_pidc.h5"
#
nrounds: 0
nsamples: 0
nobs: 0
nvars: 0
mode:
  - "puc_lmr_dist"
tbase: "2"
save_nodes: False
save_node_pairs: True
