h5ad_file: "./data/pbmc_scrna/rsc.3k/adata_lei.100k.3k.h5ad"
misi_data_file: "./out/pbmc100K.03K/adata.100K.3K.dmisidata.h5"
hist_data_file: "./out/pbmc100K.03K/adata.100K.3K.hist.h5"
puc_file: "./out/pbmc100K.03K/adata.100K.3K.lmr_puc.h5"
pidc_file: "./out/pbmc100K.03K/adata.100K.3K.lmr_pidc.h5"
#
nrounds: 0
nsamples: 0
nobs: 0
nvars: 0
mode:
  - "puc_lmr_dist"
  #- "samples_ranges"
  #- "puc2pidc"
tbase: "2"
save_nodes: False
save_node_pairs: True
