h5ad_file: "./data/pbmc/adata.20K.5K.h5ad"
row_major_h5_file: "./data/pbmc/adata.20K.5K.rmajor.h5"
misi_data_file: "./out/pbmc20K.5K/adata.20K.5K.misidata.h5"
puc_file: "./out/pbmc20K.5K/adata.20K.5K.lmr_puc.h5"
pidc_file: "./out/pbmc20K.5K/adata.20K.5K.lmr_pidc.h5"
#
nrounds: 0
nsamples: 0
nobs: 0
nvars: 0
mode:
  - misi
tbase: "e"
save_nodes: False
save_node_pairs: True
